FROM node:20.19-slim

# Set the working directory.
WORKDIR /app

# Copy package.json and package-lock.json to the container.
COPY package.json yarn.lock ./

# Install dependencies.
RUN yarn global add @angular/cli@17
RUN yarn install

# Expose the port used by the development server.
EXPOSE 4200
