version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "5000:80"

    ng-dev:
        image: ng-dev
        container_name: parseport-ng
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        command: ng serve --host 0.0.0.0 --poll 200 --disable-host-check
        expose:
            - "4200"
        volumes:
            - ./frontend:/app

    dj-dev:
        image: dj-dev
        container_name: parseport-dj
        build: backend
        env_file: .env
        profiles: ["dev"]
        command: python manage.py runserver 0.0.0.0:8000
        expose:
            - "8000"
        volumes:
            - ./backend:/src

    # dj-prod:
    #     <<: *base-dj
    #     profiles: ["prod"]
    #     command: gunicorn -b 0.0.0.0:8000 wsgi:application --pythonpath=/private

    spindle:
        container_name: spindle
        restart: always
        build:
            context: ../spindle-server
            args:
                - SPINDLE_PORT=${SPINDLE_PORT}
        expose:
            - ${SPINDLE_PORT}

    latex:
        container_name: latex
        restart: always
        build:
            context: ../latex-service
            args:
                - LATEX_PORT=${LATEX_PORT}
        image: latex-service
        expose:
            - ${LATEX_PORT}

networks:
    parseport:
        driver: bridge
