version: "3"

x-dj-base: &base-dj
    container_name: dj
    build: ./backend
    env_file: .env
    ports:
        - "8000:8000"

services:
    ng:
        container_name: ng
        build:
            context: frontend
            args:
                - CONFIGURATION=${CONFIGURATION}
        ports:
            - "8080:80"

    dj-dev:
        <<: *base-dj
        profiles: ["dev"]
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/src
        # volumes:
        #     - ../:/data
        #     - ./backend:/src
        #     - ../../private:/private

    # dj-prod:
    #     <<: *base-dj
    #     profiles: ["prod"]
    #     command: gunicorn -b 0.0.0.0:8000 wsgi:application --pythonpath=/private

    spindle:
        container_name: spindle
        build:
            context: ../spindle-server
            args:
                - SPINDLE_PORT=${SPINDLE_PORT}
        expose:
            - ${SPINDLE_PORT}
        restart: always
        # image: spindle-server

    latex:
        container_name: latex
        build:
            context: ../latex-service
            args:
                - LATEX_PORT=${LATEX_PORT}
        image: latex-service
        expose:
            - ${LATEX_PORT}
        # restart: always

networks:
    parseport:
        driver: bridge
